### ISSUE TITLE
Like Functionality

### ISSUE THREAD

**Issue by tinobragaa** [tinobragaa/eire-settlers#25]
As a User, I want to be able to like comments posted by other users so that I can express appreciation or agreement with their contributions.

### Acceptance Criteria
- Users should have the option to like comments by clicking on a designated "Like" button or icon.
- Each user should be limited to liking a comment only once to prevent abuse or spamming.
- The number of likes received by a comment should be displayed next to the "Like" button for visibility.

### Tasks
- [x] Design the user interface component for the comment "Like" button or icon.
- [x] Implement logic to update the number of likes for a comment and display it dynamically.
- [x] Style the "Like" button or icon to visually indicate the user's action when clicked.
