### ISSUE TITLE
Saved Articles Functionality

### ISSUE THREAD

**Issue by tinobragaa** [tinobragaa/eire-settlers#26]
As a User, I want to be able to save articles that I find interesting or want to revisit late so that I can easily access and reference them at a later time.

### Acceptance Criteria
- Users should have the option to save articles by clicking on a designated "Save" button or icon.
- Saved articles should be stored in a user-specific list for easy retrieval.
- Users should be able to view their list of saved articles in a dedicated section of the application.

### Tasks
- [x] Design the user interface component for the "Save" button or icon on articles.
- [x] Develop frontend functionality to allow users to save and unsave articles.
- [x] Populate the saved articles section with the user's saved selections and relevant information.
