### ISSUE TITLE
Create Branded Home Page with Latest Articles Display

### ISSUE THREAD

**Issue by tinobragaa** [tinobragaa/eire-settlers#9]
As a user when I log in, I want to be able to access the latest articles so I am up to date with the user's discussions. 

### Acceptance Criteria
- Make the index page in the home app.
- Display articles on the home in order of newest created.
- Ensure that the homepage includes branding and essential information about the site.

### Tasks
- [x] Add query sets into the home template view to display the latest articles.
- [x] Add an appealing image with a call to action for user-friendliness.
- [x] Update template with newest articles and styling.
